# Generated by Django 5.1.2 on 2025-10-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('orcid', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('keyword', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('doi', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publishing_year', models.IntegerField()),
                ('abstract', models.TextField()),
                ('citations_count', models.IntegerField()),
                ('link', models.URLField(max_length=2000)),
                ('paper_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('acc_type', models.CharField(choices=[('MEMBER', 'Member'), ('RESEARCHER', 'Researcher'), ('ADMIN', 'Admin')], default='MEMBER', max_length=50)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.keywords')),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.papers')),
            ],
        ),
        migrations.CreateModel(
            name='Author_Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.authors')),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.papers')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.authors')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.keywords')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_app.users')),
            ],
        ),
    ]
