# Generated by Django 5.1.2 on 2025-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='orcid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
