# Generated by Django 5.1.2 on 2025-10-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_type',
            field=models.CharField(max_length=20),
        ),
    ]
