# Generated by Django 5.1.2 on 2025-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_authors_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
