# Generated by Django 5.1.2 on 2025-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_keywords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
