# Generated by Django 5.1.2 on 2025-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_alter_authors_id_alter_keywords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='orcid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
