# Generated by Django 5.1.2 on 2025-11-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_alter_keywords_id'),
        ('dashboard_app', '0005_alter_authors_orcid'),
    ]

    operations = [
    ]
