# Generated by Django 5.1.2 on 2025-11-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_merge_0004_alter_keywords_id_0005_alter_authors_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_papers',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.authors'),
        ),
        migrations.AlterField(
            model_name='author_papers',
            name='doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.papers'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='orcid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='keywords_paper',
            name='doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.papers'),
        ),
        migrations.AlterField(
            model_name='keywords_paper',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.keywords'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.authors'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.users'),
        ),
        migrations.AlterField(
            model_name='users_keywords',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.keywords'),
        ),
        migrations.AlterField(
            model_name='users_keywords',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.users'),
        ),
        migrations.AlterUniqueTogether(
            name='author_papers',
            unique_together={('doi', 'author_id')},
        ),
        migrations.AlterUniqueTogether(
            name='keywords_paper',
            unique_together={('doi', 'keyword_id')},
        ),
    ]
